### PR TITLE
Return an empty data structure and not null.

### PR DESCRIPTION
**Pull request by kgryte**

### CODE REVIEW

**Comment by Planeshifter** [comment]
All looks well to me. `sqrt( [null] )` returns `[0]`, but this is the behaviour of `Math.sqrt`, so people should be aware of it. On the other hand, we make `sqrt( null )` to throw an error, so it might be a bit strange.

**Comment by kgryte** [comment]
@Planeshifter This should be ready for review again.

**Comment by Planeshifter** [comment]
Made some little changes in the documentation and parameter naming. Publish?

**Comment by kgryte** [comment]
Thanks!

**Pull request merged**
